services:
  backend:
    image: registry.richardhaddad.fr/homenet-backend:latest
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    ports:
      - "8081:8081"
      - "50051:50051"
    volumes:
      - ./backend/db:/app/db
    environment:
      - NODE_ENV=production

  frontend:
    image: registry.richardhaddad.fr/homenet-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5174:80"
    # volumes:
    #   - ./frontend:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
