/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/updateDeviceUserMetadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateDeviceUserMetadata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/removeDevice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["removeDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/getDevicesFull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDevicesFull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/getDevicesUserMetadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDevicesUserMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        GetDeviceFull: {
            deviceList: (components["schemas"]["Omit"] & {
                /** @enum {string} */
                os: "UNKNOWN_OS" | "OPENWRT_GLINET" | "HAOS" | "PROXMOX" | "ANDROID_TV" | "WINDOWS" | "DEBIAN" | "UNRECOGNIZED";
                /** @enum {string} */
                type: "PROXMOX" | "UNRECOGNIZED" | "UNKNOWN_TYPE" | "DEVICE" | "DOCKER";
                meta: components["schemas"]["Meta"];
            })[];
            instanceList: (components["schemas"]["Omit"] & {
                /** @enum {string} */
                os: "UNKNOWN_OS" | "OPENWRT_GLINET" | "HAOS" | "PROXMOX" | "ANDROID_TV" | "WINDOWS" | "DEBIAN" | "UNRECOGNIZED";
                /** @enum {string} */
                type: "PROXMOX" | "UNRECOGNIZED" | "UNKNOWN_TYPE" | "DEVICE" | "DOCKER";
                meta: components["schemas"]["Meta"];
            })[];
            appList: (components["schemas"]["Omit2"] & {
                /** @enum {string} */
                slug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
                /** @enum {string} */
                vpnMode: "UNRECOGNIZED" | "UNKNOWN_VPN" | "CLIENT" | "SERVER";
                meta: components["schemas"]["Meta"];
            })[];
            agentMetadataList: (components["schemas"]["AgentMetadata"] & {
                id: string;
                deviceId: string;
                time: number;
            })[];
            netEntityMap: {
                [key: string]: components["schemas"]["NetEntity"];
            };
        };
        Omit: {
            unknownOS?: string;
            lan: string;
            wan?: string;
            ddns?: string;
            dhcp: components["schemas"]["AgentInstance_AgentDHCPItem"][];
            web: components["schemas"]["AgentWebItem"][];
            ssh?: components["schemas"]["AgentSSH"];
            id: string;
            parentId?: string;
        };
        AgentInstance_AgentDHCPItem: {
            address: string;
            alias: string;
        };
        AgentWebItem: {
            port?: number;
            ssl: boolean;
            paths: string[];
        };
        AgentSSH: {
            ports: number[];
        };
        Meta: {
            name: string;
            description: string;
        };
        Omit2: {
            web: components["schemas"]["AgentWebItem"][];
            id: string;
            parentId: string;
            /** @description docker exec wireguard wg show */
            vpnAddress?: string;
            /**
             * @description /etc/config/wireguard_server
             *     docker exec wireguard wg show
             */
            vpnClients: string[];
            /**
             * @description /etc/nginx
             *     /etc/caddy/Caddyfile
             */
            reverseProxy: components["schemas"]["AgentApp_AgentReverseProxy"][];
            gRPC?: components["schemas"]["AgentGRPC"];
        };
        AgentApp_AgentReverseProxy: {
            fromDomain: components["schemas"]["AgentApp_AgentReverseProxy_From"];
            toAddress: components["schemas"]["AgentApp_AgentReverseProxy_To"];
        };
        AgentApp_AgentReverseProxy_From: {
            domain: string;
            ssl: boolean;
        };
        AgentApp_AgentReverseProxy_To: {
            address: string;
            ssl: boolean;
            port?: number;
        };
        AgentGRPC: {
            port: number;
        };
        AgentMetadata: {
            releaseTag: string;
            computeStartTime: number;
            computeDuration: number;
            env: {
                [key: string]: string;
            };
        };
        NetEntity: {
            id: string;
            lan: string;
            lanAliases?: string[];
            wan?: string;
            ddns?: string;
            vpn?: string;
            innerDomains?: string[];
            addressList: components["schemas"]["NetAccessAddressOnly"][];
            os: components["schemas"]["NetAccess"][];
            apps: components["schemas"]["Record"];
        };
        NetAccessAddressOnly: {
            /** @constant */
            type: "address-only";
            /** @enum {string} */
            scope: "lan" | "wan" | "dns-domain" | "vpn";
            address: string;
        };
        NetAccess: {
            /** @enum {string} */
            type: "web" | "ssh" | "grpc";
            /** @enum {string} */
            scope: "lan" | "wan" | "dns-domain" | "vpn";
            address: string;
            port?: number;
            ssl?: boolean;
            path?: string;
            href: string;
        };
        Record: {
            UNRECOGNIZED: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            DOCKER: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            UNKNOWN_APP: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            HOMENET: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            WIREGUARD: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            NGINX: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            CADDY: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            ADGUARD_HOME: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            NODE_RED: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            ZIGBEE2MQTT: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            PLEX: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            SUNSHINE: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            UPTIME_KUMA: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            NTFY: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            MOONLIGHT: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            CODE_SERVER: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            DOCKER_REGISTRY: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
            DOCKER_REGISTRY_UI: (components["schemas"]["NetAccess"] & {
                /** @enum {string} */
                appSlug: "UNRECOGNIZED" | "DOCKER" | "UNKNOWN_APP" | "HOMENET" | "WIREGUARD" | "NGINX" | "CADDY" | "ADGUARD_HOME" | "NODE_RED" | "ZIGBEE2MQTT" | "PLEX" | "SUNSHINE" | "UPTIME_KUMA" | "NTFY" | "MOONLIGHT" | "CODE_SERVER" | "DOCKER_REGISTRY" | "DOCKER_REGISTRY_UI";
            })[];
        };
        DefaultErrorShape: {
            message: string;
            /** @enum {number} */
            code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
            data: components["schemas"]["DefaultErrorData"];
        };
        DefaultErrorData: {
            /** @enum {string} */
            code: "PARSE_ERROR" | "BAD_REQUEST" | "INTERNAL_SERVER_ERROR" | "NOT_IMPLEMENTED" | "BAD_GATEWAY" | "SERVICE_UNAVAILABLE" | "GATEWAY_TIMEOUT" | "UNAUTHORIZED" | "PAYMENT_REQUIRED" | "FORBIDDEN" | "NOT_FOUND" | "METHOD_NOT_SUPPORTED" | "TIMEOUT" | "CONFLICT" | "PRECONDITION_FAILED" | "PAYLOAD_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "UNPROCESSABLE_CONTENT" | "PRECONDITION_REQUIRED" | "TOO_MANY_REQUESTS" | "CLIENT_CLOSED_REQUEST";
            httpStatus: number;
            path?: string;
            stack?: string;
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: components["schemas"]["DefaultErrorShape"];
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type GetDeviceFull = components['schemas']['GetDeviceFull'];
export type Omit = components['schemas']['Omit'];
export type AgentInstanceAgentDhcpItem = components['schemas']['AgentInstance_AgentDHCPItem'];
export type AgentWebItem = components['schemas']['AgentWebItem'];
export type AgentSsh = components['schemas']['AgentSSH'];
export type Meta = components['schemas']['Meta'];
export type Omit2 = components['schemas']['Omit2'];
export type AgentAppAgentReverseProxy = components['schemas']['AgentApp_AgentReverseProxy'];
export type AgentAppAgentReverseProxyFrom = components['schemas']['AgentApp_AgentReverseProxy_From'];
export type AgentAppAgentReverseProxyTo = components['schemas']['AgentApp_AgentReverseProxy_To'];
export type AgentGrpc = components['schemas']['AgentGRPC'];
export type AgentMetadata = components['schemas']['AgentMetadata'];
export type NetEntity = components['schemas']['NetEntity'];
export type NetAccessAddressOnly = components['schemas']['NetAccessAddressOnly'];
export type NetAccess = components['schemas']['NetAccess'];
export type Record = components['schemas']['Record'];
export type DefaultErrorShape = components['schemas']['DefaultErrorShape'];
export type DefaultErrorData = components['schemas']['DefaultErrorData'];
export type ResponseError = components['responses']['Error'];
export type $defs = Record<string, never>;
export interface operations {
    updateDeviceUserMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    deviceId: string;
                    /** @enum {string} */
                    theme: "default" | "mauve" | "blue" | "green" | "yellow";
                    name?: string;
                    /** @enum {string} */
                    type?: "server" | "router" | "mediacenter" | "desktop" | "cloud";
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result: Record<string, never>;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    removeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    deviceId: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result: Record<string, never>;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getDevicesFull: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result: {
                            data: components["schemas"]["GetDeviceFull"];
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getDevicesUserMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result: {
                            data: {
                                [key: string]: {
                                    deviceId: string;
                                    /** @enum {string} */
                                    theme: "default" | "mauve" | "blue" | "green" | "yellow";
                                    name?: string;
                                    /** @enum {string} */
                                    type?: "server" | "router" | "mediacenter" | "desktop" | "cloud";
                                };
                            };
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
