events { }

http {
  include       mime.types;
  default_type  application/octet-stream;

  access_log  /var/log/nginx/access.log;
  error_log  /var/log/nginx/error_log;

  server {
    listen 80 http2;

    location /api {
      proxy_pass http://localhost:8081;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
    }

    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /index.html;
    }
  }
  
  server {
    listen 50051; 
    http2 on;

    location / {
      grpc_pass grpc://localhost:50051;
    }
  }
}
