export const env = {
    VITE_BACKEND_API: import.meta.env.VITE_BACKEND_API,
    VITE_STATIC_DEVICES_PATH: import.meta.env.VITE_STATIC_DEVICES_PATH,
    VITE_STATIC_METADATA_PATH: import.meta.env.VITE_STATIC_METADATA_PATH,
    VITE_SAFE_MODE: import.meta.env.VITE_STATIC_METADATA_PATH,
};
