name: Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Install protoc & dependencies
        working-directory: agent
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
          unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"

          export GO111MODULE=on
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          export PATH="$PATH:$(go env GOPATH)/bin"

      - name: Generate gRPC code
        working-directory: agent
        run: make gen-grpc

      - name: Install Go dependencies
        working-directory: agent
        run: make install-deps

      - name: Build for ARM 32bits
        working-directory: agent
        run: make build-arm-32

      - name: Build for Linux 64bits
        working-directory: agent
        run: make build-linux-64

      - name: Build for Windows 64bits
        working-directory: agent
        run: make build-windows-64

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.repository.updated_at }}
          prerelease: false
          draft: false
          files: agent/dist/*
          generate_release_notes: false
          name: ${{ github.event.repository.updated_at }}
          body: |
            Release ${{ github.event.repository.updated_at }}
