name: Release

on:
  push:
    branches:
      - main
    # paths:
    #   - agent/**
  pull_request:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Format commit tag
        id: tag
        run: |
          formatted_date=$(date -d "${{ github.event.head_commit.timestamp }}" +'v%Y%m%dT%H%MZ')
          echo "tag=$formatted_date" >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Install protoc & dependencies
        working-directory: agent
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
          unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"

          export GO111MODULE=on
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          export PATH="$PATH:$(go env GOPATH)/bin"

      - name: Generate gRPC code
        working-directory: agent
        run: make gen-grpc

      - name: Install Go dependencies
        working-directory: agent
        run: make install-deps

      - name: Create draft release
        # uses: softprops/action-gh-release@v2
        # with:
        #   token: ${{ secrets.RELEASE_PAT_TOKEN }}
        #   tag_name: ${{ steps.tag.outputs.tag }}
        #   prerelease: false
        #   draft: true
        #   generate_release_notes: false
        #   name: ${{ steps.tag.outputs.tag }}
        #   body: |
        #     Release ${{ steps.tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT_TOKEN }}
        run: |
          gh release create ${{ steps.tag.outputs.tag }} --draft --title "${{ github.event.repository.updated_at }}" --notes "Release ${{ github.event.repository.updated_at }}"

      - name: Build for ARM 32bits
        working-directory: agent
        env:
          RELEASE_ID: ${{ steps.create_release.outputs.id }}
        run: make build-arm-32

      - name: Build for Linux 64bits
        working-directory: agent
        env:
          RELEASE_ID: ${{ steps.create_release.outputs.id }}
        run: make build-linux-64

      - name: Build for Windows 64bits
        working-directory: agent
        env:
          RELEASE_ID: ${{ steps.create_release.outputs.id }}
        run: make build-windows-64

      - name: Update release with uploads
        # uses: softprops/action-gh-release@v2
        # with:
        #   token: ${{ secrets.RELEASE_PAT_TOKEN }}
        #   tag_name: ${{ steps.tag.outputs.tag }}
        #   prerelease: false
        #   draft: false
        #   files: agent/dist/*
        #   generate_release_notes: false
        #   name: ${{ steps.tag.outputs.tag }}
        #   body: |
        #     Release ${{ steps.tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT_TOKEN }}
        run: |
          gh release upload ${{ steps.tag.outputs.tag }} agent/dist/agent_arm agent/dist/agent_linux agent/dist/agent_windows.exe
          gh release edit ${{ steps.tag.outputs.tag }} --draft=false

      # - name: Upload ARM asset
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.RELEASE_PAT_TOKEN }}
      #     file: agent/dist/agent_arm
      #     asset_name: agent_arm
      #     tag: ${{ github.ref }}
      #     overwrite: true
      #     body: "This is my release text"

      # - name: Upload ARM Asset
      #   uses: actions/upload-release-asset@1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.RELEASE_PAT_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./agent/dist/agent_arm
      #     asset_name: agent_arm
      #     asset_content_type: application/octet-stream

      # - name: Publish Release
      #   uses: eregon/publish-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.RELEASE_PAT_TOKEN }}
      #   with:
      #     release_id: ${{ steps.create_release.outputs.id }}
