name: Deploy Agent

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - .github/workflows/deploy-agent.yml
  #     - agent/**
  # pull_request:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Format commit tag
        id: tag
        run: |
          formatted_date=$(date -d "${{ github.event.head_commit.timestamp }}" +'0.0.%Y%m%d%H%M')
          echo "tag=$formatted_date" >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Install protoc & dependencies
        working-directory: agent
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
          unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"

          export GO111MODULE=on
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          export PATH="$PATH:$(go env GOPATH)/bin"

      - name: Generate gRPC code
        working-directory: agent
        run: make gen-grpc

      - name: Install Go dependencies
        working-directory: agent
        run: make install-deps

      # - name: Create draft release
      #   id: create_release
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ secrets.RELEASE_PAT_TOKEN }}
      #     script: |
      #       const response = await github.rest.repos.createRelease({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         tag_name: "${{ steps.tag.outputs.tag }}",
      #         name: "${{ steps.tag.outputs.tag }}",
      #         draft: true,
      #         prerelease: false,
      #         generate_release_notes: false,
      #       });
      #       core.setOutput('id', response.data.id);

      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT_TOKEN }}
        run: |
          gh release create ${{ steps.tag.outputs.tag }} --draft --title "Homenet Agent ${{ steps.tag.outputs.tag }}" --notes "Release ${{ steps.tag.outputs.tag }}"

      - name: Build for ARM 32bits
        working-directory: agent
        env:
          RELEASE_TAG: ${{ steps.tag.outputs.tag }}
        run: make build-arm-32

      - name: Build for Linux 64bits
        working-directory: agent
        env:
          RELEASE_TAG: ${{ steps.tag.outputs.tag }}
        run: make build-linux-64

      - name: Build for Windows 64bits
        working-directory: agent
        env:
          RELEASE_TAG: ${{ steps.tag.outputs.tag }}
        run: make build-windows-64

      - name: Update release with uploads
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT_TOKEN }}
        run: |
          gh release upload ${{ steps.tag.outputs.tag }} agent/dist/agent-linux-arm agent/dist/agent-linux-amd64 agent/dist/agent-windows-amd64.exe
          gh release edit ${{ steps.tag.outputs.tag }} --draft=false
