name: Deploy Frontend only

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "**"
  #     - "!.github/workflows/deploy-agent.yml"
  #     - "!agent/**"
  #     - "!.vscode/**"
  #     - "!**/*.md"
  #     - "!**/.gitignore"
  # pull_request:

jobs:
  deploy-front-only:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker build
        run: docker build . --target frontend-only -t registry.chnapy.dev/homenet-front

      - name: Configure Wireguard VPN
        if: env.WG_CONFIG
        env:
          WG_CONFIG: ${{ secrets.WG_CONFIG }}
        run: |
          sudo apt install wireguard resolvconf
          echo "${{ secrets.WG_CONFIG }}" > /tmp/wg0.conf
          sudo chmod 600 /tmp/wg0.conf
          sudo wg-quick up /tmp/wg0.conf

      - name: Docker push
        run: docker push registry.chnapy.dev/homenet-front
