name: Deploy Frontend & Backend

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!.github/workflows/deploy-agent.yml"
      - "!agent/**"
      - "!.vscode/**"
      - "!**/*.md"
      - "!**/.gitignore"
  pull_request:

jobs:
  deploy-front-back:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Format commit tag
      #   id: tag
      #   run: |
      #     formatted_date=$(date -d "${{ github.event.head_commit.timestamp }}" +'0.0.%Y%m%d%H%M')
      #     echo "tag=$formatted_date" >> $GITHUB_OUTPUT

      - name: Install WireGuard
        run: sudo apt-get update && sudo apt-get install -y resolvconf wireguard

      - name: Docker build
        run: docker build . -t registry.richardhaddad.fr/homenet

      - name: Open WireGuard tunnel
        run: |
          echo "${{ secrets.WG_CONFIG }}" > wg0.conf
          sudo wg-quick up ./wg0.conf

          # debug DNS
          # echo "resolv.conf before changes"
          # echo -e "nameserver 10.0.0.1\nnameserver 8.8.8.8\nsearch ." | sudo tee /etc/resolv.conf
          # echo "resolv.conf after changes"
          sudo cat /etc/resolv.conf 
          # nslookup registry-1.docker.io
          # curl https://registry-1.docker.io/v2/
          nslookup registry.richardhaddad.fr
          curl https://registry.richardhaddad.fr/v2/

      - name: Docker push
        run: docker push registry.richardhaddad.fr/homenet

      - name: Close WireGuard tunnel
        if: always()
        run: sudo wg-quick down ./wg0.conf

      - name: Set up SSH 🔑
        run: |
          mkdir -vm 700 $HOME/.ssh
          ssh-keyscan -H vps-0c88ff97.vps.ovh.net > $HOME/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

      - name: Update remote containers ⬆️
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@vps-0c88ff97.vps.ovh.net 'docker pull registry.richardhaddad.fr/homenet \
            && docker stop homenet 2> /dev/null || true \
            && docker rm homenet 2> /dev/null || true \
            && docker run --name homenet -d -v ~/homenet/db:/app/db -p 50051:50051 --network main_default registry.richardhaddad.fr/homenet \
            && docker container prune -f \
            && docker image prune -af'
